### ISSUE TITLE
find-and-replace-multi-items.ps1 column name check

### ISSUE THREAD

**Issue by kegregoi** [claytonfuselier/code-monkey#22]
Please add a check to ensure that the needed column names ("OldString" and "NewString") are in the .csv before the scan starts. I had added the column names, but forgot to save the file before running the script and the scanning portion gets pretty messed up :)

**Comment by claytonfuselier** [comment]
Added validation for CSV file path and that the CSV contains the needed headers "OldString" and "NewString".
